# Generated by Django 3.1.5 on 2021-03-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type_guests', models.CharField(choices=[('Вики Роднини', 'Вики Роднини'), ('Илиан Роднини', 'Илиан Роднини'), ('Вики Приятели', 'Вики Приятели'), ('Илиан Приятели', 'Илиан Приятели'), ('Кумове', 'Кумове'), ('Шаферки', 'Шаферки')], max_length=50)),
                ('slug_name', models.CharField(max_length=70, unique=True)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
