# Generated by Django 3.1.5 on 2021-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0004_guest_is_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_vegetarian',
            field=models.CharField(choices=[('Не', 'Не'), ('Да', 'Да')], default='Не', max_length=2),
        ),
    ]
