# Generated by Django 3.1.5 on 2021-03-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0005_auto_20210312_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='guests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wedd_app.guest'),
            preserve_default=False,
        ),
    ]
