# Generated by Django 3.1.5 on 2021-03-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0006_invitation_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='guests',
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wedd_app.invitation'),
            preserve_default=False,
        ),
    ]
