# Generated by Django 3.1.5 on 2021-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0007_auto_20210312_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
