# Generated by Django 3.1.5 on 2021-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0008_invitation_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='accept_invitation',
            field=models.CharField(choices=[('Приемам', 'Приемам поканата с удоволствие'), ('Отказвам', 'Любезно отказвам поканата')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
