# Generated by Django 3.1.5 on 2021-03-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0009_guest_accept_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='table_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wedd_app.table'),
            preserve_default=False,
        ),
    ]
