# Generated by Django 3.1.5 on 2021-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0010_auto_20210312_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='free_places',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
