# Generated by Django 3.1.5 on 2021-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0011_table_free_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
