# Generated by Django 3.1.5 on 2021-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0012_auto_20210312_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='accept_invitation',
            field=models.CharField(blank=True, choices=[('Приемам', 'Приемам поканата с удоволствие'), ('Отказвам', 'Любезно отказвам поканата')], max_length=50),
        ),
    ]
