# Generated by Django 3.1.7 on 2021-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0015_auto_20210319_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(blank=True),
        ),
    ]
