# Generated by Django 3.1.5 on 2021-03-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0022_auto_20210323_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='guests',
        ),
        migrations.AddField(
            model_name='guest',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wedd_app.invitation'),
        ),
    ]
