# Generated by Django 3.1.5 on 2021-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0023_auto_20210323_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='invitation',
        ),
        migrations.AddField(
            model_name='invitation',
            name='guests',
            field=models.ManyToManyField(to='wedd_app.Guest'),
        ),
    ]
