# Generated by Django 3.1.5 on 2021-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0027_auto_20210324_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainguest',
            name='is_vegetarian',
            field=models.CharField(blank=True, choices=[('Не', 'Не'), ('Да', 'Да')], max_length=2),
        ),
    ]
