# Generated by Django 3.1.5 on 2021-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0032_auto_20210324_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainguest',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mainguest',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mainguest',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='secondguest',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
