# Generated by Django 3.1.5 on 2021-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0033_auto_20210324_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondguest',
            name='email',
        ),
    ]
