# Generated by Django 3.1.5 on 2021-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedd_app', '0034_remove_secondguest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainguest',
            name='email',
            field=models.EmailField(blank=True, error_messages={'required': 'Please Enter your Name'}, max_length=50),
        ),
    ]
